### ISSUE TITLE
Possible dynamic maxValue, minValue, labels and zones?

### ISSUE THREAD

**Issue by sanhuaaan** [amroessam/vgauge#1]
Hello,
I'm using **v-gauge** for showing data retrieved from server. It's working ok if I set the options, maxValue and minValue as static values. But I'd want to be able to modify these values with the information from the server. Right now, I'm assigning the gauge value this way: 

`<v-gauge class="v-gauge"
                 :value="getValue()"
                 :options="options"
                 :animationSpeed="15"
                 :minValue="0"
                 :maxValue="300"
                 gaugeValueClass="gauge-value"
                 unit="mg/dl"
                 :top="true"/>`

`getValue () {
      return parseInt(this.getStatus.value);
    },`

Is there any chance to be able to assign new values to the staticLabels.labels, staticZones, minValue and maxValue when receiving data from the server (as I'm doing now with "value" prop)?

Thanks!

**Comment by sanhuaaan** [comment]
Nevermind. I solved it adding a `v-if="getValue()"` to v-gauge component.

**Comment by amroessam** [comment]
Another option would be binding the minValue and maxValue to a computer property that change on an update
