### ISSUE TITLE
Example for gaugeValueClass

### ISSUE THREAD

**Issue by WoJoosen** [amroessam/vgauge#10]
Could I please get an example for the `gaugeValueClass`? I can't figure out how to use it in any way and I'm not even sure if it does what I want it to do. I want to change the style of my `value` text. Right now it's ugly (small and white) I want to make it bigger and move it in the middle of the gauge. Please help me.

Thanks

**Comment by amroessam** [comment]
Hi @MobKill3r2006, you can find an example of how to use [`deep`](https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors) in the [sandbox on line 62](https://codesandbox.io/s/jz3qoxny63?file=/src/App.vue:1165-1176)

Please let me know if you need further explanation. If not, please close the issue.

**Comment by WoJoosen** [comment]
Thank you for your answer. I sincerely appreciate it. But I still can't figure some stuff out. How do I assign that class to the gaugeValueClass? This is what I have now:
```
<style scoped>
>>> span {
  text-align: center;
  font-weight: bold;
  display: block;
}
...
</style>
```
How would I tell the gaugeValueClass property to use this? Thanks again in advance.

**Comment by amroessam** [comment]
Oh sorry if I didn't explain it well. 
1. define a css class let's say `potato`

```css
<style scoped>
...
>>> potato {
  font-size: 40px;
  font-weight: bold;
  color: purple;
}
</style>
```
2. Then assign it to the `gaugeValueClass` attribute like so
```html
    <v-gauge :value="x" top gaugeValueClass="potato"/>
```

Should work!

**Comment by WoJoosen** [comment]
It's really not your fault :) but for some reason it still wont work (I'm so sorry for being such a pain). This is what I am doing:
```
<style scoped>
>>> potato {
  font-size: 40px;
  font-weight: bold;
  color: purple;
}
</style>
```
Then I am defining it in my object:
```
<v-gauge :value="value" :options="options" :width="width" :height="height" gaugeValueClass="potato" />
```
However it still shows as:
![image](https://user-images.githubusercontent.com/24656938/80637130-c5e68800-8a5e-11ea-868a-438b30da296c.png)
Also, this is a visual of my code:
![image](https://user-images.githubusercontent.com/24656938/80637235-f0384580-8a5e-11ea-9b00-a48cddd90f11.png)
I am sharing this because it seems to give an "error". I am not sure if this is just a visual bug or if it really is something I did wrong.

I thank you again for your answers and help :)

**Comment by amroessam** [comment]
Oh shoot, I forgot to add the dot for css classes. It has to be like this

```css
<style scoped>
...
>>> .potato {
  font-size: 40px;
  font-weight: bold;
  color: purple;
}
</style>

**Comment by WoJoosen** [comment]
Thank you so much :D 
Sorry for the stupidity, I don't know much about html/css, especially vue.js, so I had to figure a lot out myself, and this I couldn't really find. Thank you so much!

**Comment by amroessam** [comment]
Of course, any time!

**Comment by simeon9696** [comment]
Sometimes you may get an error unless specify a selector: 

```
<style scoped>
...
* >>> .potato {
  font-size: 40px;
  font-weight: bold;
  color: purple;
}
</style>
```
