### ISSUE TITLE
further fix on memory leak

### ISSUE THREAD

**Issue by chiu0602** [amroessam/vgauge#12]
Please use latest gaugeJS build (v1.3.7). After that, the library will be leak free.

@amroessam Thanks for your excellent work!

**Comment by amroessam** [comment]
Amazing work @chiu0602, doing it now!!

**Comment by chiu0602** [comment]
The package downloaded from npm site haven't been built
`npm i vgauge@1.2.12-rc1`

Please help to build it, thanks a lot!

**Comment by amroessam** [comment]
Hahaha, i forgot to build it before publishing. I'll do that now!

**Comment by amroessam** [comment]
Done! 383f179

**Comment by chiu0602** [comment]
I have downloaded rc1 and rc2 through npm command, the files' content in `dist` folder are the same

**Comment by amroessam** [comment]
So the files in `dist` would stay the same, the only difference would be in the package.json referencing latest gaugeJS build (v1.3.7) as per your recommendation. Hope that helps!

**Comment by chiu0602** [comment]
After modifying `package.json`, please run `npm i` and then `npm run build`

**Comment by amroessam** [comment]
Done, try now!

**Comment by chiu0602** [comment]
Thanks~ it is perfect now.
