### ISSUE TITLE
 Failed to execute 'addColorStop' on 'CanvasGradient

### ISSUE THREAD

**Issue by cacalot123** [amroessam/vgauge#15]
Failed to execute 'addColorStop' on 'CanvasGradient

**Comment by amroessam** [comment]
Please provide some code

**Comment by cacalot123** [comment]
const option = {
          angle: 0.3, // The span of the gauge arc  0。1--0.49
          lineWidth: 0.07, // The line thickness
          radiusScale: 1, // Relative radius  大小
          pointer: {
            length: 0.6, // // Relative to gauge radius
            strokeWidth: 0.035, // The thickness
            color: '#000000' // Fill color
          },
          limitMax: false, // If false, max value increases automatically if value > maxValue
          limitMin: false, // If true, the min value of the gauge will be fixed
           colorStart: '#000000' , // Colors 内弧度开始颜色
           colorStop: '#ffffff' , // just experiment with them
          strokeColor: '#cccccc', // to see which ones work best for you
          generateGradient: true,
          highDpiSupport: true // High resolution support
        }

**Comment by amroessam** [comment]
Please refer to https://bernii.github.io/gauge.js/
