### ISSUE TITLE
Running multiple charts on same page

### ISSUE THREAD

**Issue by ringmybell** [amroessam/vgauge#16]
Found your vgauge chart package for use with Vue but I can not figure out how to run two charts on the same page if they have **different** styles - for example I want one solid grey count down timer and the other to show a measurement within a range with the red/yellow/green sections of the chart. Like this

![image](https://user-images.githubusercontent.com/30030587/98514987-76f79600-22be-11eb-8f4c-6ee197ce9d20.png)

Is it possible to do this with vgauge? With the gaugeJS chart using html/js/css I could just set up two functions with different options in each and call up the one I want, but I can't figure out how to do this with Vue as all charts seem to reference the same data & options (it seems I can not have two options in the data file), which implies all charts on that webpage need look the same. I am new to Vue so I have probably missed something, any clarification appreciated.

**Comment by amroessam** [comment]
You can do the same by providing two different objects to options property :)

**Comment by ringmybell** [comment]
Thanks, I have two charts running now. My issue was I has put a `}` instead of a `},` when closing the first options function, I am still getting used to some of the Vue syntax. 

But now having issues where I can set some properties like options and max width working, but I can't vary the animation speed, min or max values.  I am not using a .vue file, my code is similar to your html example https://codesandbox.io/s/vgauge-browser-include-32hxf?file=/index.html

It seems you can not change the animation speed, min or max values using the following

`<v-gauge :value="x" :animationSpeed=10 :minValue=0 :maxValue=30 :width="width"/>`

It must be called some other way but I am new to Vue, I can't get it working. Any tips appreciated, or if you can put a quick example on the sandbox changign the above html example with the other parameters would be great.

**Comment by ringmybell** [comment]
I think I have managed to solve this. I will put it here incase anyone else gets tripped up on this.  The parameters need to be in Kebab form not Camel form

This does not work  `<v-gauge :value="x" :animationSpeed=10 :minValue=0 :maxValue=30 :width="width"/>`

This seems to work  `<v-gauge :value="x" :animation-speed=10 :min-value=0 :max-value=30 :width="width"/>`
