### ISSUE TITLE
Dynamic change max value

### ISSUE THREAD

**Issue by ringmybell** [amroessam/vgauge#17]
I am trying to change the gauge max value based on a dynamic input.  I am trying to link this input these two parameters. In the index.js file I am trying to alter staticZone value `max: 15`, this alters where the gauge color bar starts and ends

`staticZones: [{strokeStyle: "#b8b8b8", min: 0, max: 15} ],` 

and in index.html I am trying to change value ` :max-value=15` which changes the maximum value the gauge counts down from. I want to make them both equal to the same value and change based on input from Node-Red.

```
<v-gauge 
   :value="countDownTimeData" unit="seconds" 
   :options="optionsCountdownTimer" 
   :animation-speed=10
   :min-value=0
   :max-value=15           
   :width="widthCountdownTime" />               
</td></tr>
```
I can get the gauge to work fine if I hard code in the number values, but if I try to make them variable then it wont work. 

I have tried almost every possible permutation I can think of from v:bind to v:if to using mostache braces{{}} to using functions from within computed and methods, but I can't get anything to work properly. 

If you have any tips on how I can change these parameters that would be great.

**Comment by amroessam** [comment]
This is a vue
