### ISSUE TITLE
Props Options

### ISSUE THREAD

**Issue by AzO755** [amroessam/vgauge#2]
do you have an example of using the props options please?

**Comment by AzO755** [comment]
It's ok 

`import VGauge from "vgauge";

export default {
  components: {
    VGauge
  },
  
  data() {
    return {
      noozle : 0,
      options: {
            type: Object,
            angle: 0.1,
            lineWidth: 0.44,
            radiusScale: 1,
            pointer: {
                length: 0.6,
                strokeWidth: 0.035,
                color: "#000000"
            },
            limitMax: false,
            limitMin: false,
            colorStart: "#6FADCF",
            colorStop: "#8FC0DA",
            strokeColor: "#E0E0E0",
            generateGradient: true,
            highDpiSupport: true
        }
    };
  },`

**Comment by amroessam** [comment]
Yes that's exactly how you pass options to the gauge
